#!/bin/bash

echo "Watching and compiling files with babel..."

cd /soflow/src

babel \
  --copy-files \
  --ignore node_modules \
  --out-dir /soflow/compiled \
  --source-maps inline \
  --watch \
  . &

cd /soflow/compiled

nodemon \
  --delay 0.5 \
  --quiet \
  --watch lib \
  --watch tests \
  --watch devops \
  --exec "devops/unit-tests; eslint --color $SRC_DIR/lib $SRC_DIR/integration-tests" &

wait
