version: '2'

services:
  dev:
    build: .
    volumes:
      - .:/src:cached
    environment:
      SOFLOW_SWF_DOMAIN: SoFlow
      SOFLOW_NAMESPACE: $USER-sftest
      SOFLOW_WORKFLOWS_VERSION: test
