#!/bin/bash

passThroughArgs=()

while test $# -gt 0
do
  case "$1" in
    --watch)
      watchRequested=1
      ;;
    *)
      passThroughArgs+=($1)
      ;;
  esac
  shift
done

if [[ $watchRequested ]]; then
  watchexec \
    --watch lib/ \
    --watch test/ \
    "$0 $passThroughArgs"
  exit 0
fi


SOFLOW_ROOT_NAMESPACE=$SOFLOW_NAMESPACE
export SOFLOW_NAMESPACE=${SOFLOW_NAMESPACE}-$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 9 | head -n 1)

echo -e "\n# Integration tests"
echo -e "# namespace: $SOFLOW_NAMESPACE"

node test/scripts/setup.js
cd test # work around ava watching issue
ava "**/*.test.js" -c 8 -T 10s $passThroughArgs
failed=$?
cd ..

# Cleanup
export SOFLOW_NAMESPACE=$SOFLOW_ROOT_NAMESPACE
node test/scripts/teardown.js
node test/scripts/clean-up-s3-buckets.js $SOFLOW_ROOT_NAMESPACE

[[ $failed -eq 1 ]] && exit 1

exit 0
